/*
 * generated by Xtext 2.12.0
 */
package org.eclipse.xtext.example.fowlerdsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class StatemachineStandaloneSetup extends StatemachineStandaloneSetupGenerated {

	def static void doSetup() {
		new StatemachineStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
