/*
 * generated by Xtext 2.12.0
 */
package org.eclipse.xtext.example.fowlerdsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class StatemachineRuntimeModule extends AbstractStatemachineRuntimeModule {
}
