/*
 * generated by Xtext 2.12.0
 */
package org.eclipse.xtext.example.fowlerdsl.ide


/**
 * Use this class to register ide components.
 */
class StatemachineIdeModule extends AbstractStatemachineIdeModule {
}
