/*
 * generated by Xtext 2.12.0
 */
package org.eclipse.xtext.example.fowlerdsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.example.fowlerdsl.ui.internal.FowlerdslActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class StatemachineExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FowlerdslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return FowlerdslActivator.getInstance().getInjector(FowlerdslActivator.ORG_ECLIPSE_XTEXT_EXAMPLE_FOWLERDSL_STATEMACHINE);
	}
	
}
